Parksil00
my-js-study/js-calculator pull request #1
Opened 2022-03-13 18:46 UTC by parksil0

my-js-study:parksil0

2022-03-14 14:55 UTC, yujo11 requested changes
안녕하세요 박실님!

전체적으로 메서드와 함수들이 책임과 역할에 따라 적절하게 분리되어 있어서 코드를 읽기 좋았네요!

몇가지 코멘트 남겼으니 확인해주시고 다시 리뷰요청 해주세요! 고생하셨습니다! 👍 👍 👍

2022-03-14 14:55 UTC, yujo11 commented on cypress/integration/calculator.spec.js
> +    cy.get('.operation').contains('=').click();
```
1. 숫자 클릭 
2. 연산자 클릭
3. 숫자 클릭
4. "=" 클릭
```

위에 적은 1 ~ 4 의 내용이 대부분 테스트에서 반복되어 사용되고 있는데 함수로 분리해보시면 어떨까요?

2022-03-14 14:55 UTC, yujo11 commented on src/js/Calculator.js
> +  }
이렇게 요소들을 순회하면서 하나씩 이벤트를 등록해주는거보다 이벤트 위임을 이용해보시면 좋을거 같아요!

2022-03-14 14:55 UTC, yujo11 commented on src/js/Calculator.js
> +    const digitValue = element.innerText;
`textContent`에 대해서도 찾아보시면 좋을거 같아요!

2022-03-14 14:55 UTC, yujo11 commented on src/js/Calculator.js
> +        return Math.floor(Number(leftValue) / Number(rightValue));
`-3.3`과 같은 음수에 `Math.floor()`를 사용해도 원하는 결과가 나올까요?

2022-03-14 14:55 UTC, yujo11 commented on src/js/helpers.js
> +}
`qs`의 경우 "querySelector"의 약자도 될 수 있지만 `qs`라는 유명한 라이브러리가 `QueryString`을 핸들링하는 라이브러리이기 때문에 이 라이브러리가 먼저 생각이 났네요. 다른 네이밍을 고려해보시면 좋을거 같습니다!

2022-03-14 14:55 UTC, yujo11 commented on src/js/helpers.js
> +}
`on`이라는 이름으로 이 함수가 어떤 역할을 하는지 전혀 유추할 수 없었는데요. 

길어도 이름만으로 함수의 역할을 알 수 있도록 고민해보시면 어떨까요?

2022-03-14 14:55 UTC, yujo11 commented on src/js/Calculator.js
> +  }
상수로 정의해둔 `MAX_DIGITS`와 비교해서 결과를 반환해주는 함수인데 `ThreeDigits`라는 이름이 함수에 명시적으로 들어가있는게 어색해보이네용

2022-03-14 14:55 UTC, yujo11 commented on src/js/Calculator.js
> +    }
연산자를 찾는거라면 `Array.find()` 같은 메서드를 사용하는게 더 적절할거 같네용

2022-03-14 14:55 UTC, yujo11 commented on src/js/Calculator.js
> +    }
이 조건 때문에 연속적인 계산이 막히는 경우가 있네요.

```
1. 3 - 3  = 0
2. + 클릭 시, alert가 나옴
```

2022-03-14 15:35 UTC, parksil0 commented on cypress/integration/calculator.spec.js
> +    cy.get('.operation').contains('=').click();
중복되는 부분이 있어 좀 불편한 감이 있었는데, 테스트 환경에서 함수로 분리하려는 생각은 안 해봤던 것 같아요!
의견 감사합니다~

2022-03-14 15:35 UTC, parksil0 commented on src/js/Calculator.js
> +  }
넵 한번 찾아볼게요!

2022-03-14 15:36 UTC, parksil0 commented on src/js/Calculator.js
> +        return Math.floor(Number(leftValue) / Number(rightValue));
음.. 알고리즘 개선을 다시 해보겠습니다~!

2022-03-14 15:37 UTC, parksil0 commented on src/js/helpers.js
> +}
qs, qsAll, on같은 함수는 이전부터 계속 사용해 오던 거라 별 생각 없이 썼었는데, 모르는 사람의 입장에서 보면 모호하다고 생각할 수 있겠네요.

2022-03-14 15:38 UTC, parksil0 commented on src/js/Calculator.js
> +    }
먼저 테스트에 계산 오류 들을 먼저 만들어보고 오류 들을 잡아볼게요!

2022-03-15 15:34 UTC, Tanney-102 reviewed
안녕하세요 박실님!
리뷰가 많이 늦었습니다ㅠㅠㅠㅠ

간단한 미션에 걸맞게 간결하게 잘 구현해주신 것 같아요!
그런데 데모에서 연속되는 계산이 조금 문제가 있어보입니다!
'1+2+3' 과 같은 계산에서 현재는 '1+2'까지만 고려가 되어있네요 ㅎㅎ
또 '1-2' 연산을 통해 -1을 얻은 후에 '-1+3'과 같은 계산을 하면 -1이 출력되는 버그가 있습니다.
이 부분도 첫번째 연산자를 기준으로 계산을 하기 때문에 생기는 문제 같습니다.

해당 이슈 해결하시면서 남겨놓은 코멘트들도 확인해주세요!

2022-03-15 15:34 UTC, Tanney-102 commented on .eslintrc.js
> +  },
rule에 prettier에 대한 내용이 없는 것 같아요!
prettierrc의 설정이 실제 적용되고 있는지 확인해보셔야할 것 같습니다

2022-03-15 15:34 UTC, Tanney-102 commented on package.json
> +    "test": "./node_modules/.bin/cypress open",
여기 커맨드는 `cypress open`으로 충분할 것 같습니다.

2022-03-15 15:34 UTC, Tanney-102 commented on cypress/integration/calculator.spec.js
> +    cy.get('.operation').contains('=').click();
https://docs.cypress.io/api/cypress-api/custom-commands

2022-03-15 15:34 UTC, Tanney-102 commented on cypress/integration/calculator.spec.js
> +describe('계산기 초기 화면 테스트', () => {
연속적인 계산 (예를들어 2+4x2 를 한 번에 계산하거나, 이번 결과값에서 이어 계산하는 경우)을 포함 할 것인지 결정하고 테스트 내용에도 포함되면 좋을 것 같습니다.
지금 데모에서는 연속적인 계산이 제대로 되지 않고 있습니다~

2022-03-15 15:34 UTC, Tanney-102 commented on cypress/integration/calculator.spec.js
> +    cy.visit('http://127.0.0.1:5500/index.html');
끝에 index.html을 붙여 줘야하나요?

2022-03-15 15:34 UTC, Tanney-102 commented on src/js/Calculator.js
> +  }
더불어 handle~~ 와 같은 네이밍은 주로 이벤트 핸들러에 사용합니다.
```js
bindEvents() {
   on(this.digits, 'click', this.handleClickDigits.bind(this))
}
```
이런식으로 명확하게 함수 안에서 어떤 일이 벌어지는지 가능한 명확하게 명시해주는 것이 좋습니다!

2022-03-15 15:34 UTC, Tanney-102 commented on src/js/Calculator.js
> +  }
totalValue에서 operator를 하나만 찾기에는 '1+2-3' 과 같은 입력도 가능한 상태입니다.
여러연산자를 한 번에 처리하도록 하거나, 여러 연산자를 입력할 수 없도록 해야할 것 같아요!

2022-03-15 15:34 UTC, Tanney-102 commented on src/js/helpers.js
> +}
querySelector는 `$`로 qeurySelectorAll은 `$$`로 많이 사용합니다

2022-03-15 15:34 UTC, Tanney-102 commented on src/js/index.js
> +new Calaulator();
인스턴스가 의미없이 생성만 되고 있습니다.
꼭 클래스로 구현했어야했는지 고민해볼 수 있는 지점이라고 생각해요!
calculator 인스턴스가 필요할걸까요 아니면 앱 실행을 위한 함수 호출 한 번이 필요한 걸까요?

2022-03-15 20:31 UTC, parksil0 commented on .eslintrc.js
> +  },
제가 eslint 설정을 잘 몰라서 그러는데, prettier 설정은 extends에서 설정하면 되는 거 아니였나요?
prettierrc에서 설정 값을 변경한 후 포맷팅 했을 때 잘 적용되는 것 같거든요.

2022-03-15 21:30 UTC, parksil0 commented on src/js/index.js
> +new Calaulator();
이전에도 몇 번 실행의 용도로 인스턴스를 받지 않고 실행만 했었거든요.

함수로 실행하는 것과 클래스로 실행하는 것과 차이가 있나요?

2022-03-15 21:46 UTC, parksil0 commented
안녕하세요!

꼼꼼한 리뷰 감사합니다 😄 

덕분에 많이 배우고, 많이 개선했어요 ㅎㅎ

그리고, `on`이라는 이름을 가진 이벤트 리스너 함수가 알고보니 [jQuery](https://api.jquery.com/on/)에서 파생된 이름이더라고요 ㅋㅋㅋ 그것도 모르고 이전부터 사용하니까 별 생각 없이 사용한 것 같아요.
함수 이름을 변경하자니 길어지고, 길어지다보니 굳이 사용할 필요가 없는 것 같아 `on` 함수는 지웠습니다~!

다음은 변경 목록입니다!

* 중복되어 사용되는 cypress api를 custom command로 변경 : 04928a8dcfdec6270722e46fa2499ac180edaf86
* 각 버튼 이벤트 위임 : c64a412f11517f6fd3deeae96b0833f748a42d47
* `innerText` -> `textContext`로 변경 : 8159598cc3ec6b12dc0f8a3190651da01c9cd6a5
* 음수 결과 값에서 소수점을 없앨 때에는 버림이 아닌, 올림 처리
   * 테스트 코드 :  720dcd0ae84fd621580b7d3727874051444ccb76
   * 구현 코드 : 0054d8daf5ebf84185d226eb0473f226f104b726
* 유틸함수 이름 수정 (`qs` -> `$`, `qsAll` -> `$$`): 2f131a309c278bdc7d963c2e143ce6ab7ad35f00
* `on` 함수 삭제 : e7ff196a7d124d16334eea1a709237fdac025dd0
* 문맥 상 맞지 않는 함수명 변경(checkOverThreeDigits -> checkOverMaxDigits) : 9a97aeb327e443e17358e6e97ace1fbb1c867b16
* 명령형(`for`) -> 선언형(`Array.find()` 사용) : 1262816b1fecd451caf2502cb4c343c9e54b5492
* 연속적인 계산이 되도록 기능 추가
   * 테스트 코드 : 271812449f64737cc4c97f66b88868202ba3d47a
   * 구현 코드 : 56446e7eb655195f72e722cf02c943551a45221a
* 테스트 코드 중 불필요한 url 제거 : d5c7d3752bdd99cd0d1e40c3da5d98c290d270a9
* cypress 테스트 명령어(script) 변경 : 803025521b18af5089e9662b1f3333a6cf2c8bc3
* class에서 function으로 변경 : 0e28c731d162b9c2b0fdedb27b8e8e65e4c79555

혹시, 잘 못된 부분 있으면 리뷰 부탁드리겠습니다..!
끝으로, 따로 시간 내 리뷰 해 주셔서 너무 너무 고맙습니다!

2022-03-16 00:12 UTC, parksil0 commented
> 이렇게 로직 상으로도 처리가 가능하지만 `Math.trunc()`를 염두에 두고 말씀드린 내용이었습니다 `Math.trunc()`를 사용하시면 소수점을 "버림" 처리 할 수 있거든요!
> 
> * https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc

오... 생각지도 못했어요. 이렇게 활용할 수도 있군요. 감사합니다!

그리고, 리뷰 반영했어요! [9026f6a](https://github.com/my-js-study/js-calculator/pull/1/commits/9026f6ad7493122e728d37dcbd9bbc2f38a425f9)

2022-03-18 11:12 UTC, yujo11 approved these changes
안녕하세요 박실님~ 

리뷰 반영을 잘 해주셨군요!

코멘트 몇개 남겨두긴 했는데 이 코멘트들은 다음 미션 수행하면서 반영해보시면 좋을거 같습니다! 고생하셨습니다!

2022-03-18 11:12 UTC, yujo11 commented on cypress/integration/calculator.spec.js
> +    cy.clickOperation('=');
`clickDigit` -> `clickOperation` -> `clickDigit` 이렇게 반복되는 패턴도 함수로 만들 수 있지 않을까요?

2022-03-18 11:12 UTC, yujo11 commented on src/js/Calculator.js
> +    ac.addEventListener('click', handleClickAC.bind(this));
이 부분은 이벤트 위임을 사용한다면 하나의 이벤트 리스너만 등록해도 처리가 가능할거 같네요

2022-03-18 11:12 UTC, yujo11 commented on src/js/Calculator.js
> +  };
지금 함수가 한 번에 여러 개의 역할을 동시에 수행하고 있는거 같아요. 하나의 함수가 하나의 역할만 하도록 분리해봐도 좋을거 같습니다

2022-03-18 12:00 UTC, Tanney-102 commented on .eslintrc.js
> +  },
`extends: ["prettier"]` 또는 `extends: ["eslint-config-prettier"]`는 'eslint-config-prettier' 파일의 내용을 가져옵니다(prettier와 겹치는 eslint rule들을 off 해줌)
prettier가 eslint 에러로 잡히도록 하는 플러그인이 eslint-plugin-prettier입니다.
따라서 플러그인에도 추가를 해줘야 하고 실제 rule도 지정을 해줘야합니다.
```json
// .eslintrc
{
    ....

    "plugin": ["prettier"],
    "rules": {
        "prettier/prettier": "error"
    }
}
```
요런식으로요

찾아보니까 .eslintrc에
```json
{
    "extends": ["plugin:prettier/recommende"]
}
```
를 넣어주면 위 설정이 포함된 파일을 알아서 extends 한다고는 하네요 ㅎㅎ
대신 이 경우 임의의 prettier설정이 들어갈 수 있으니 직접 설정하시는 걸 권장합니다.

참고: https://github.com/prettier/eslint-plugin-prettier#readme

2022-03-18 12:02 UTC, Tanney-102 commented on .eslintrc.js
> +  },
그리고 제가 놓친 부분이 하나있네요!
```suggestion
  rules: {
    'import/prefer-default-export': 'error',
  },
```
요렇게 해주셔야합니다.

https://eslint.org/docs/user-guide/configuring/rules#rules

2022-03-18 12:53 UTC, Tanney-102 commented on src/js/index.js
> +new Calaulator();
실행 결과에 차이는 없겠지만 new 연산자를 단순 함수 호출처럼 사용하는게 클래스의 사용 목적과 맞지 않다고 생각해 드린 코멘트였습니다~ 주어진 도구는 가능한 목적에 맞게 (적어도 어울리게) 사용하는 것이 맞겠죠!

클린코드의 관점에서도 그리 좋은 방법은 아니라고 생각합니다.
`new Calculator()` 라는 표현은 Calculator 인스턴스가 생성되었다는 사실말고는 아무런 말도 하지 않습니다. 
어떤 로직을 수행하는건지, DOM에 이벤트를 붙이는 건지 알 방법이 없습니다.
```js
const calculator = new Calculator()
calculator.initialize()
```
라던가

```js
const calculator = new Calculator()
calculator.bindEvents()
```
정도만 되었어도 의미가 명확했겠죠 ㅎㅎㅎ
하얀 백지에 '계산기' 라고 써있는 것과 '계산기를 초기화합니다.' 라고 써있는 것 사이에 사소하지만 확실한 뉘앙스 차이가 있는 것처럼 코드에서도 이러한 차이가 있음을 이해하는 게 중요하다고 생각합니다.

(여기서부터는 조금 다른 맥락입니다)
또 한 가지 드는 생각이 있는데요!
`new Calculator`로 충분했다는 게 한 편으로는 생성자가 필요 이상의 책임을 지고 있었기 때문은 아닐까하는 생각이 듭니다.
이전 클래스 코드에서는 생성자 안에서 이벤트를 바인딩하고 있었는데, 과연 이게 좋은 패턴인지는 고민해볼 여지가 있는 것 같습니다.
생성자는 생성만하고 각 라이프 사이클 단계에 있는 메서드들의 호출은 독립적으로 이뤄져야 이 인스턴스를 다루는게 더 수월하지 않을까하는 생각이 드네요 ㅎㅎ 물론 지금처럼 작은 앱에서는 크게 중요한 문제는 아닌 것 같습니다.

2022-03-18 13:03 UTC, Tanney-102 reviewed
피드백 반영하느라 고생하셨습니다!
지난 피드백과 수정하신 부분에 대해 간단히 코멘트 달았습니다!

2022-03-18 13:03 UTC, Tanney-102 commented on src/js/Calculator.js
> +function Calculator() {
지금처럼 모든 유틸함수나 이벤트 핸들러들을 함수안에서 정의하면 Calculator 함수가 호출될때마다 모두 다시 선언될 것 같아요! DOM select도 마찬가지구요~
module을 사용하는 이상 scope은 보장이 되니 안에 있는 변수나 함수들을 모두 밖으로 빼내면 어떨까요?
```js
const total = $('#total')
...

function bindEvents() { ... }

...
...
...

function initializeCalculatorApp() {
    bindEvents()
}
```
요 정도로 구성하고 initializeCalculatorApp만 밖으로 export하면 충분할 것 같아요

2022-03-18 13:03 UTC, Tanney-102 commented on src/js/Calculator.js
> +function Calculator() {
혹은 bindEvents를 조금 더 구체적인 이름으로(Calculator App 사용을 위한 이벤트를 바인딩 하는 것이 잘 드러날 수 있도록) 바꾸고 바로 export 해도 좋겠네요!

2022-03-20 16:14 UTC, parksil0 commented
안녕하세요! 리뷰 주신 부분 반영했습니다.

덕분에 클린하게 코드를 짜는 방법에 대해 많이 배웠어요. 고맙습니다!

 * eslintrc rules 재설정 : [4660930](https://github.com/my-js-study/js-calculator/pull/1/commits/4660930dc6f517d39f70c64a9eabd61c4b8cb746)
* test 파일 내의 반복적인 api를 custom command로 재설정 : [a592161](https://github.com/my-js-study/js-calculator/pull/1/commits/a59216142efab69310944ebc0b05c2620c016eaf)
* 이벤트 위임 재설정 : [1fdcc1f](https://github.com/my-js-study/js-calculator/pull/1/commits/1fdcc1f515703b8b83a5776156f5574e7d8ed8c8), [4d484ae](https://github.com/my-js-study/js-calculator/pull/1/commits/4d484aebf2f902c8587450d228c44fd71b8f111b)
* if else를 switch case로 역할을 보다 분명하게 리팩토링 : [96173ce](https://github.com/my-js-study/js-calculator/pull/1/commits/96173ceafb58c1b0cb23202887b49e3fbe9086b0)
* calculator 파일 내의 함수 모듈화: [fbb43a7](https://github.com/my-js-study/js-calculator/pull/1/commits/fbb43a79689769af793d77b5d3f67ad23cc65e27)

혹시 제가 잘 못 이해하고 커밋 한 부분이 있으시면 리뷰 부탁 드립니다..! 감사합니다 😄

2022-03-21 04:00 UTC, Tanney-102 commented
리뷰 반영감사합니다!
이제 이 미션은 마무리하셔도 좋을 것 같습니다!

2022-03-21 04:00 UTC, Tanney-102 approved these changes

2022-03-21 08:54 UTC, yujo11 approved these changes
리뷰 모두 잘 반영해주신거 확인했습니다!

고생하셨습니다! 👍 👍 👍

2022-03-21 09:09 UTC, merged